### ISSUE TITLE
AttributeError: 'NoneType' in Motor class in __del__ function

### ISSUE THREAD

**Issue by Jumji-py** [ChristophGaukel/ev3-python3#12]
I've just started following the documentation for ev3_dc and currently I'm on using motors ([from this website](https://ev3-dc.readthedocs.io/en/latest/examples_motor.html)). When I run the following script:
```
import ev3_dc as ev3

with ev3.Motor(
    ev3.PORT_B,
    protocol=ev3.USB,
    host='00:16:53:42:2B:99'
) as my_motor:
    print(f'the port, where this motor is connected to: {my_motor.port}')
```

The Code works and outputs the message, but it is then followed by an error:
```
the port, where this motor is connected to: 2
Exception ignored in: <function Motor.__del__ at 0x00000180D39395E0>
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\ev3_dc\motor.py", line 232, in __del__
AttributeError: 'NoneType' object has no attribute '_introspection'
```
Is there some way to fix this error?

**Comment by ChristophGaukel** [comment]
Thanks for your feedback. I expect, you are not the only person with this behavior. On your windows system python seems to behave different from my linux system. I have done a small modification in the deletion logic. 

Please do these steps:

- upgrade your ev3_dc with: `pip install --upgrade ev3_dc` (this replaces version 0.9.10 by version 0.9.10.1)
- again run your program

It would be nice to hear, if this solves the problem.

Kind regards,
Christoph

**Comment by Jumji-py** [comment]
@ChristophGaukel It's working now properly and there are no more errors, thanks for the help.
