### ISSUE TITLE
Just a suggestion

### ISSUE THREAD

**Issue by Pedro-Beirao** [ChristophGaukel/ev3-python3#4]
I made a rubiks cube solver (inspired by mindcuber) using this library. The docs (https://ev3-dc.readthedocs.io/en/latest/intro.html) says to use   **time.sleep()**   to give some time for the motor to run, but this made my robot slow and sometimes had problems. You should add a function that uses   **while motor.busy: pass**    or at least have some examples of this on the docs.

I'd be happy to do it btw

**Comment by ChristophGaukel** [comment]
Hallo,
I suppose you use methods start_move_to and start_move_by. If you instead use methods move_to and move_by, which returns a thead_task and then you start it with keyword argument thread=False, you will see the performance you expect. Please look at the examle in section move_to:

import ev3_dc as ev3

with ev3.Motor(
    ev3.PORT_B,
    protocol=ev3.USB,
    host='00:16:53:42:2B:99'
) as my_motor:
    (
        my_motor.move_by(360, brake=True) +
        my_motor.move_by(-360)
    ).start(thread=False)

Kind regards
Christoph

**Comment by Pedro-Beirao** [comment]
Ohh you are right I use start_move_to. Didnt know there was a difference.
Thanks

**Comment by ChristophGaukel** [comment]
Hallo,

bad news: my tests with hid on a windows machine failed. Reading returns empty messages. This says: pyusb and hid, both seem to fail on at least one system. May be, we can solve your problems on macOS. Give me a chance!

On Unix systems, the permissions of USB devices is handled very specific. I added this udev-rule on my ubuntu system as file /etc/udev/rules.d/90-legoev3.rules:

ATTRS{idVendor}=="0694",ATTRS{idProduct}=="0005",MODE="0666",GROUP="christoph"

This allows all members of group christoph (me allone), to read from and write to any mounted LEGO EV3 device. After adding or changing udev-ules, you need to reboot or run:

sudo udevadm control --reload

As far as I know, macOS is very close to Unix. Maybe, you can use pyusb together with libusb, when you add a udev-rule.
Can you please test it for me? I don't own a Mac.

Kind regards,
Christoph
