### ISSUE TITLE
Read RGB values from the color sensor

### ISSUE THREAD

**Issue by Steve-Zheng** [ChristophGaukel/ev3-python3#7]
Hi, I would like to build a Rubik's cube solver using ev3_dc. I want to read the RGB values from the color sensor, but this is not implemented yet. I tried to implement it on my own and I got some weird results. Here is my code and I also printed the color using ev3.Color().color. 

```
import ev3_dc as ev3
import struct

ev3device = ev3.EV3(protocol=ev3.USB, host='00:16:53:83:D8:4D')
ev3device.verbosity = 1

ops = b''.join((
    ev3.opInput_Device,  # operation
    ev3.READY_RAW,  # CMD
    ev3.LCX(0),  # LAYER
    ev3.PORT_2,  # NO
    ev3.LCX(29),  # TYPE (EV3-Color)
    ev3.LCX(4),  # MODE (RGB)
    ev3.LCX(3),  # VALUES
    ev3.GVX(0),  # VALUE1 (R)
    ev3.GVX(4),  # VALUE1 (G)
    ev3.GVX(8),  # VALUE1 (B)
))
reply = ev3device.send_direct_cmd(ops,global_mem=12)
print(reply)
fmt = "<%di" % 3
values=struct.unpack(fmt,reply)
print(values)

color = color = (
    'none',
    'black',
    'blue',
    'green',
    'yellow',
    'red',
    'white',
    'brown'
)[ev3.Color(port=ev3.PORT_2,ev3_obj=ev3device).color]
print(color)
```

My discovery is that this code performs well when detecting red and green, but not blue. The value for blue is less than what it should be. Here are some test results.

Actual: red
Output:
```
(170, 39, 10)
red
```

Actual: green
Output:
```
(30, 136, 15)
green
```

Actual: white
Output:
```
(199, 272, 122)
white
```

Actual: blue
Output:
```
(30, 94, 67)
blue
```

Using ev3.Color().color, the result is correct. However, it does not match the RGB values when the object is blue.

Also, I found that the values can sometimes be larger than 255, and I don't know whether that is acceptable or not.

Can you please help me to check my code? I would be really appreciated if you could add reading RGB values to the Color class.

Thank you!

**Comment by ChristophGaukel** [comment]
Hi,
great, that you use my package and congratulations that you already are that deep in the details. Your question really helped me to understand mode RGB.

The issue with values larger than 255:
If you use both, READY_RAW (fmt='<3i', global_mem=12) and READY_PCT (fmt='3B', global_mem=3), then you can divide the raw RGB values by the percentage RGB values and you will see results close to 1024, which says: you need to divide your READY_RAW results by 4 to get, what you want to get.

The problem with the blue color:
The measurement is done with reflected light and consequently depends on the color spectrum of the light source. If the blue part of the light source's frequencies is under-represented, then you will get a result, where blue also is under-represented. Use your values from the white surface to do a white balance and you will see more realistic results.

According to your advice, I will add RGB mode to the Color class.

Kind regards,
Christoph

**Comment by ChristophGaukel** [comment]
RGB mode has been added to the Color class.
