### ISSUE TITLE
Support for Gyrosensor

### ISSUE THREAD

**Issue by Jackomatrus** [ChristophGaukel/ev3-python3#9]
Is there any chance to add a Gyrosensor? Unfortunatly I have no idea about the communication protocol for the EV3 sensors, but it would be extremely useful to a lot of projects.

**Comment by Jackomatrus** [comment]
Since all ther classes were written and documented well, I was able to create the class myself - see pull request below.
https://github.com/ChristophGaukel/ev3-python3/pull/10

**Comment by ChristophGaukel** [comment]
Hi,
I merged your pull request, thanks a lot. I think, we need to document the usage. Please send me a short example program in the style of the documentation. Or even better, you update the documentation and I merge it?

Kind regards,
Christoph

**Comment by Jackomatrus** [comment]
Please excuse any errors as I'm new to Github and have never written an .rst file before.
https://github.com/ChristophGaukel/ev3-python3/pull/11
